"""BigMarker tap class."""

from typing import List

from singer_sdk import Tap, Stream
from singer_sdk import typing as th  # JSON schema typing helpers

from tap_bigmarker.streams import (
    BigMarkerStream,
    ChannelsStream,
    ChannelsSubscribersStream,
    ChannelsAdminsStream,
    ChannelsConferencesStream,
    ChannelsConferencesStatsStream,
    ConferencesStream,
    ConferencesAttendeesStream,
    ConferencesHandoutsStream,
    ConferencesSurveysStream,
    ConferencesPresentersStream,
    ConferenceDetailStream,
    ConferenceCustomFieldsStream,
    ConferenceAssociatedSessionsStream,
    ConferenceRecurringChildrenStream,
    ConferenceRecordingStatusStream,
    ConferenceRecordingViewsStream,
    ConferenceAdminUrlStream,
    ConferenceTranscriptUrlStream,
    ConferenceStatsUrlStream,
    ConferencesRegistrantsStream,
    ConferencesRegistrationsLiveStream,
    ConferencesAttendeesLiveStream,
    ConferencesAttendeesOnDemandStream,
    ConferencesRegistrationsNoShowsStream,
    ConferencesRegistrationsQaStream,
    ConferenceRegistrationsSimpleStream,
    ConferenceCheckedInRegistrantsStream,
    ConferenceAutomationsTimelineStream,
    ConferenceChatTranscriptStream,
    ConferencePollTranscriptStream,
    ConferenceOfferTranscriptStream,
    ConferenceEventSummaryStream,
    ConferenceEnterExitLogStream,
    ConferencePresenterEngagementStream,
    ConferenceAttendanceMonitorDataStream,
    CustomEmailSeedStream,
    CustomEmailStatisticsStream,
    CustomEmailSuppressionsStream,
    CustomEmailAnalyticsStream,
    ConferenceHandoutDownloadDataStream,
    ConferenceDialInListStream,
    ConferenceIntegrationSettingsStream,
    ConferenceActivityLogsStream,
    ChannelRegistrationsStream,
    ChannelRegisteredConferencesStream,
    ChannelBlockListStream,
    ConferenceRegistrationBlockListStream,
    MeetingSpaceSeedStream,
    MeetingSpaceDetailStream,
)

STREAM_TYPES = [
    ChannelsStream,
    ChannelsSubscribersStream,
    ChannelsAdminsStream,
    ChannelsConferencesStream,
    ChannelsConferencesStatsStream,
    ConferencesStream,
    ConferencesHandoutsStream,
    ConferencesSurveysStream,
    ConferencesPresentersStream,
    ConferencesAttendeesStream,
    ConferencesRegistrantsStream,
    ConferencesRegistrationsLiveStream,
    ConferencesAttendeesLiveStream,
    ConferencesAttendeesOnDemandStream,
    ConferencesRegistrationsNoShowsStream,
    ConferencesRegistrationsQaStream,
    ConferenceDetailStream,
    ConferenceCustomFieldsStream,
    ConferenceAssociatedSessionsStream,
    ConferenceRecurringChildrenStream,
    ConferenceRecordingStatusStream,
    ConferenceRecordingViewsStream,
    ConferenceAdminUrlStream,
    ConferenceTranscriptUrlStream,
    ConferenceStatsUrlStream,
    ConferenceRegistrationsSimpleStream,
    ConferenceCheckedInRegistrantsStream,
    ConferenceAutomationsTimelineStream,
    ConferenceChatTranscriptStream,
    ConferencePollTranscriptStream,
    ConferenceOfferTranscriptStream,
    ConferenceEventSummaryStream,
    ConferenceEnterExitLogStream,
    ConferencePresenterEngagementStream,
    ConferenceAttendanceMonitorDataStream,
    CustomEmailSeedStream,
    CustomEmailStatisticsStream,
    CustomEmailSuppressionsStream,
    CustomEmailAnalyticsStream,
    ConferenceHandoutDownloadDataStream,
    ConferenceDialInListStream,
    ConferenceIntegrationSettingsStream,
    ConferenceActivityLogsStream,
    ChannelRegistrationsStream,
    ChannelRegisteredConferencesStream,
    ChannelBlockListStream,
    ConferenceRegistrationBlockListStream,
    MeetingSpaceSeedStream,
    MeetingSpaceDetailStream,
]

class TapBigMarker(Tap):
    """BigMarker tap class."""
    name = "tap-bigmarker"
    config_jsonschema = th.PropertiesList(
        th.Property(
            "api_key",
            th.StringType,
            required=True,
            description="The token to authenticate against the API service"
        ),
        th.Property(
            "api_url",
            th.StringType,
            required=True,
            description="The url for the API service"
        ),
        th.Property(
            "page_size",
            th.StringType,
            required=False,
            description="The page size for each request"
        ),
        th.Property(
            "download_bmid",
            th.StringType,
            required=False,
            description="Admin BMID used for recording/transcript/stats download URL endpoints",
        ),
        th.Property(
            "custom_email_id",
            th.StringType,
            required=False,
            description="Custom email id used for custom email analytics endpoints",
        ),
        th.Property(
            "meeting_space_id",
            th.StringType,
            required=False,
            description="Meeting space id (reserved for future endpoints)",
        ),
        th.Property(
            "integration_type",
            th.StringType,
            required=False,
            description="Integration type for conference integration settings endpoint (default: salesforce)",
        ),
        th.Property(
            "registered_conferences_email",
            th.StringType,
            required=False,
            description="Email used for channel list_registered_conferences endpoint",
        ),
        th.Property(
            "channel_block_list_type",
            th.StringType,
            required=False,
            description="List type for channel block list endpoint (default: block_list)",
        ),
        th.Property(
            "registration_block_list_type",
            th.StringType,
            required=False,
            description="List type for conference registration block list endpoint (default: block_list)",
        ),
        th.Property(
            "custom_email_action_type",
            th.StringType,
            required=False,
            description="Action type filter for custom email analytics endpoint",
        ),
        th.Property(
            "custom_email_date_start",
            th.StringType,
            required=False,
            description="Start date filter for custom email analytics endpoint",
        ),
        th.Property(
            "custom_email_date_end",
            th.StringType,
            required=False,
            description="End date filter for custom email analytics endpoint",
        ),
    ).to_dict()

    def discover_streams(self) -> List[Stream]:
        """Return a list of discovered streams."""
        return [stream_class(tap=self) for stream_class in STREAM_TYPES]
